#ifndef COMMON_H
#define COMMON_H

#include "asm-generic/int-ll64.h"

enum {
	SNIFFER_ATTR_UNSPEC,
	SNIFFER_ATTR_RADIOTAP,
	SNIFFER_ATTR_HEADER,
	SNIFFER_ATTR_BODY,
	__SNIFFER_ATTR_MAX,
};

#define SNIFFER_FAMILY_NAME "wifi_sniffer"
#define SNIFFER_MCGRP_NAME "sniffer_frame"

#define SNIFFER_CMD_FRAME 1
#define SNIFFER_MCGRP_FRAMES 0
#define SNIFFER_ATTR_MAX (__SNIFFER_ATTR_MAX - 1)
#define N_SNIFFER_MCGRPS 1

typedef enum FRAME_DIRECTION {
	CLIENT_TO_CLIENT,
	CLIENT_TO_AP,
	AP_TO_CLIENT,
	AP_TO_AP,
} FRAME_DIRECTION;

#endif
