#ifndef ACTION_FRAME_PARSER_H
#define ACTION_FRAME_PARSER_H

#include <stdint.h>
typedef enum ACTION_CAT {
	SPECTRUM_MANAGEMENT,
	QOS,
	DLS,
	BLOCK_ACK,
	PUBLIC,
	RADIO_MEASUREMENT,
	FAST_BSS_TRANSITION,
	HT,
	SA_QUERY,
	PROTECTED_DUAL_OF_PUBLIC,
	VHT = 21,
	HE = 25,
} ACTION_CAT;

typedef enum SPECTRUM_MANAGEMENT_ACTION {
	MEASUREMENT_REQUEST,
	MEASUREMENT_REPORT,
	TPC_REQUEST,
	TPC_REPORT,
	CHANNEL_SWITCH_ANNOUNCEMENT,
} SPECTRUM_MANAGEMENT_ACTION;

typedef enum QOS_ACTION {
	ADDTS_REQUEST,
	ADDTS_RESPONSE,
	DELTS,
	SCHEDULE,
	QOS_MAP_CONF,
} QOS_ACTION;

typedef enum DLS_ACTION {
	DLS_REQUEST,
	DLS_RESPONSE,
	DLS_TEARDOWN,
} DLS_ACTION;

typedef enum BLOCK_ACK_ACTION {
	ADDBA_REQUEST,
	ADDBA_RESPONSE,
	DELBA,
} BLOCK_ACK_ACTION;

typedef enum RADIO_MEASUREMENT_ACTION {
	RADIO_MEASUREMENT_REQUEST,
	RADIO_MEASUREMENT_REPORT,
	LINK_MEASUREMENT_REQUEST,
	LINK_MEASUREMENT_REPORT,
	NEIGHBOUR_REPORT_REQUEST,
	NEIGHBOUR_REPORT_RESPONSE,
} RADIO_MEASUREMENT_ACTION;

typedef enum FAST_BSS_TRANSITION_ACTION {
	FT_REQUEST,
	FT_RESPONSE,
	FT_CONFIRM,
	FT_ACK,
} FAST_BSS_TRANSITION_ACTION;

typedef enum HT_ACTION {
	NOTIFY_CHANNEL_WIDTH,
	SM_POWER_SAVE,
	PMSP,
	SET_PCO_PHASE,
	CSI,
	NONCOMPRESSED_BEAMFORMING,
	COMPRESSED_BEAMFORMING,
	ASEL_INDICES_FEEDBACK,
} HT_ACTION;

typedef enum SA_QUERY_ACTION {
	SA_QUERY_REQUEST,
	SA_QUERY_RESPONSE,
} SA_QUERY_ACTION;

const char *action_cat_to_string(ACTION_CAT cat);
const char *action_to_string(ACTION_CAT cat, uint8_t code);
const char *spectrummgmt_action_to_string(SPECTRUM_MANAGEMENT_ACTION code);
const char *qos_action_to_string(QOS_ACTION code);
const char *dls_action_to_string(DLS_ACTION code);
const char *blockack_action_to_string(BLOCK_ACK_ACTION code);
const char *rmeasurement_action_to_string(RADIO_MEASUREMENT_ACTION code);
const char *fbsstransition_action_to_string(FAST_BSS_TRANSITION_ACTION code);
const char *ht_action_to_string(HT_ACTION code);
const char *saquery_action_to_string(SA_QUERY_ACTION code);
#endif
